//https://docs.microsoft.com/en-us/azure/cognitive-services/speech-service/language-support
export enum SpeechServiceLocale {
  Arabic_Algeria = "ar-DZ",
  Arabic_Bahrain_modern_standard = "ar-BH",
  Arabic_Egypt = "ar-EG",
  Arabic_Iraq = "ar-IQ",
  Arabic_Israel = "ar-IL",
  Arabic_Jordan = "ar-JO",
  Arabic_Kuwait = "ar-KW",
  Arabic_Lebanon = "ar-LB",
  Arabic_Libya = "ar-LY",
  Arabic_Morocco = "ar-MA",
  Arabic_Oman = "ar-OM",
  Arabic_Qatar = "ar-QA",
  Arabic_Saudi_Arabia = "ar-SA",
  Arabic_Palestinian_Authority = "ar-PS",
  Arabic_Syria = "ar-SY",
  Arabic_Tunisia = "ar-TN",
  Arabic_United_Arab_Emirates = "ar-AE",
  Arabic_Yemen = "ar-YE",
  Bulgarian_Bulgaria = "bg-BG",
  Catalan_Spain = "ca-ES",
  Chinese_Cantonese_Traditional = "zh-HK",
  Chinese_Mandarin_Simplified = "zh-CN",
  Chinese_Taiwanese_Mandarin = "zh-TW",
  Croatian_Croatia = "hr-HR",
  Czech_Czech = "cs-CZ",
  Danish_Denmark = "da-DK",
  Dutch_Netherlands = "nl-NL",
  English_Australia = "en-AU",
  English_Canada = "en-CA",
  English_Ghana = "en-GH",
  English_Hong_Kong = "en-HK",
  English_India = "en-IN",
  English_Ireland = "en-IE",
  English_Kenya = "en-KE",
  English_New_Zealand = "en-NZ",
  English_Nigeria = "en-NG",
  English_Philippines = "en-PH",
  English_Singapore = "en-SG",
  English_South_Africa = "en-ZA",
  English_Tanzania = "en-TZ",
  English_United_Kingdom = "en-GB",
  English_United_States = "en-US",
  Estonian_Estonia = "et-EE",
  Filipino_Philippines = "il-PH",
  Finnish_Finland = "fi-FI",
  French_Canada = "fr-CA",
  French_France = "fr-FR",
  French_Switzerland = "fr-CH",
  German_Austria = "de-AT",
  German_Switzerland = "de-CH",
  German_Germany = "de-DE",
  Greek_Greece = "el-GR",
  Gujarati_Indian = "gu-IN",
  Hebrew_Israel = "he-IL",
  Hindi_India = "hi-IN",
  Hungarian_Hungary = "hu-HU",
  Indonesian_Indonesia = "id-ID",
  Irish_Ireland = "ga-IE",
  Italian_Italy = "it-IT",
  Japanese_Japan = "ja-JP",
  Kannada_India = "kn-IN",
  Korean_Korea = "ko-KR",
  Latvian_Latvia = "lv-LV",
  Lithuanian_Lithuania = "lt-LT",
  Malay_Malaysia = "ms-MY",
  Maltese_Malta = "mt-MT",
  Marathi_India = "mr-IN",
  Norwegian_Bokmål_Norway = "nb-NO",
  Persian_Iran = "fa-IR",
  Polish_Poland = "pl-PL",
  Portuguese_Brazil = "pt-BR",
  Portuguese_Portugal = "pt-PT",
  Romanian_Romania = "ro-RO",
  Russian_Russia = "ru-RU",
  Slovak_Slovakia = "sk-SK",
  Slovenian_Slovenia = "sl-SI",
  Spanish_Argentina = "es-AR",
  Spanish_Bolivia = "es-BO",
  Spanish_Chile = "es-CL",
  Spanish_Colombia = "es-CO",
  Spanish_Costa_Rica = "es-CR",
  Spanish_Cuba = "es-CU",
  Spanish_Dominican_Republic = "es-DO",
  Spanish_Ecuador = "es-EC",
  Spanish_El_Salvador = "es-SV",
  Spanish_Equatorial_Guinea = "es-GQ",
  Spanish_Guatemala = "es-GT",
  Spanish_Honduras = "es-HN",
  Spanish_Mexico = "es-MX",
  Spanish_Nicaragua = "es-NI",
  Spanish_Panama = "es-PA",
  Spanish_Paraguay = "es-PY",
  Spanish_Peru = "es-PE",
  Spanish_Puerto_Rico = "es-PR",
  Spanish_Spain = "es-ES",
  Spanish_Uruguay = "es-UY",
  Spanish_USA = "es-US",
  Spanish_Venezuela = "es-VE",
  Swahili_Kenya = "sw-KE",
  Swedish_Sweden = "sv-SE",
  Tamil_India = "ta-IN",
  Telugu_India = "te-IN",
  Thai_Thailand = "th-TH",
  Turkish_Turkey = "tr-TR",
  Vietnamese_Vietnam = "vi-VN",
}

//https://docs.microsoft.com/en-us/azure/cognitive-services/speech-service/language-support#speech-translation
export enum SpeechTranslationLanguage {
  Afrikaans = "af",
  Albanian = "sq",
  Amharic = "am",
  Arabic = "ar",
  Armenian = "hy",
  Assamese = "as",
  Azerbaijani = "az",
  Bangla = "bn",
  Bosnian_Latin = "bs",
  Bulgarian = "bg",
  Cantonese_Traditional = "yue",
  Catalan = "ca",
  Chinese_Literary = "lzh",
  Chinese_Simplified = "zh-Hans",
  Chinese_Traditional = "zh-Hant",
  Croatian = "hr",
  Czech = "cs",
  Danish = "da",
  Dari = "prs",
  Dutch = "nl",
  English = "en",
  Estonian = "et",
  Fijian = "fj",
  Filipino = "fil",
  Finnish = "fi",
  French = "fr",
  French_Canada = "fr-ca",
  German = "de",
  Greek = "el",
  Gujarati = "gu",
  Haitian_Creole = "ht",
  Hebrew = "he",
  Hindi = "hi",
  Hmong_Daw = "mww",
  Hungarian = "hu",
  Icelandic = "is",
  Indonesian = "id",
  Inuktitut = "iu",
  Irish = "ga",
  Italian = "it",
  Japanese = "ja",
  Kannada = "kn",
  Kazakh = "kk",
  Khmer = "km",
  Klingon = "tlh-Latn",
  Klingon_plqaD = "tlh-Piqd",
  Korean = "ko",
  Kurdish_Central = "ku",
  Kurdish_Northern = "kmr",
  Lao = "lo",
  Latvian = "lv",
  Lithuanian = "lt",
  Malagasy = "mg",
  Malay = "ms",
  Malayalam = "ml",
  Maltese = "mt",
  Maori = "mi",
  Marathi = "mr",
  Myanmar = "my",
  Nepali = "ne",
  Norwegian = "nb",
  Odia = "or",
  Pashto = "ps",
  Persian = "fa",
  Polish = "pl",
  Portuguese_Brazil = "pt",
  Portuguese_Portugal = "pt-pt",
  Punjabi = "pa",
  Queretaro_Otomi = "otq",
  Romanian = "ro",
  Russian = "ru",
  Samoan = "sm",
  Serbian_Cyrillic = "sr-Cyrl",
  Serbian_Latin = "sr-Latn",
  Slovak = "sk",
  Slovenian = "sl",
  Spanish = "es",
  Swahili = "sw",
  Swedish = "sv",
  Tahitian = "ty",
  Tamil = "ta",
  Telugu = "te",
  Thai = "th",
  Tigrinya = "ti",
  Tongan = "to",
  Turkish = "tr",
  Ukrainian = "uk",
  Urdu = "ur",
  Vietnamese = "vi",
  Welsh = "cy",
  Yucatec_Maya = "yua",
}

export const SpeechTranslationLanguagesNames: { [id in SpeechTranslationLanguage]: string } = {
  [SpeechTranslationLanguage.Afrikaans]: "Afrikaans",
  [SpeechTranslationLanguage.Albanian]: "Albanian",
  [SpeechTranslationLanguage.Amharic]: "Amharic",
  [SpeechTranslationLanguage.Arabic]: "Arabic",
  [SpeechTranslationLanguage.Armenian]: "Armenian",
  [SpeechTranslationLanguage.Assamese]: "Assamese",
  [SpeechTranslationLanguage.Azerbaijani]: "Azerbaijani",
  [SpeechTranslationLanguage.Bangla]: "Bangla",
  [SpeechTranslationLanguage.Bosnian_Latin]: "Bosnian (Latin)",
  [SpeechTranslationLanguage.Bulgarian]: "Bulgarian",
  [SpeechTranslationLanguage.Cantonese_Traditional]: "Cantonese (Traditional)",
  [SpeechTranslationLanguage.Catalan]: "Catalan",
  [SpeechTranslationLanguage.Chinese_Literary]: "Chinese (Literary)",
  [SpeechTranslationLanguage.Chinese_Simplified]: "Chinese Simplified",
  [SpeechTranslationLanguage.Chinese_Traditional]: "Chinese Traditional",
  [SpeechTranslationLanguage.Croatian]: "Croatian",
  [SpeechTranslationLanguage.Czech]: "Czech",
  [SpeechTranslationLanguage.Danish]: "Danish",
  [SpeechTranslationLanguage.Dari]: "Dari",
  [SpeechTranslationLanguage.Dutch]: "Dutch",
  [SpeechTranslationLanguage.English]: "English",
  [SpeechTranslationLanguage.Estonian]: "Estonian",
  [SpeechTranslationLanguage.Fijian]: "Fijian",
  [SpeechTranslationLanguage.Filipino]: "Filipino",
  [SpeechTranslationLanguage.Finnish]: "Finnish",
  [SpeechTranslationLanguage.French]: "French",
  [SpeechTranslationLanguage.French_Canada]: "French (Canada)",
  [SpeechTranslationLanguage.German]: "German",
  [SpeechTranslationLanguage.Greek]: "Greek",
  [SpeechTranslationLanguage.Gujarati]: "Gujarati",
  [SpeechTranslationLanguage.Haitian_Creole]: "Haitian Creole",
  [SpeechTranslationLanguage.Hebrew]: "Hebrew",
  [SpeechTranslationLanguage.Hindi]: "Hindi",
  [SpeechTranslationLanguage.Hmong_Daw]: "Hmong Daw",
  [SpeechTranslationLanguage.Hungarian]: "Hungarian",
  [SpeechTranslationLanguage.Icelandic]: "Icelandic",
  [SpeechTranslationLanguage.Indonesian]: "Indonesian",
  [SpeechTranslationLanguage.Inuktitut]: "Inuktitut",
  [SpeechTranslationLanguage.Irish]: "Irish",
  [SpeechTranslationLanguage.Italian]: "Italian",
  [SpeechTranslationLanguage.Japanese]: "Japanese",
  [SpeechTranslationLanguage.Kannada]: "Kannada",
  [SpeechTranslationLanguage.Kazakh]: "Kazakh",
  [SpeechTranslationLanguage.Khmer]: "Khmer",
  [SpeechTranslationLanguage.Klingon]: "Klingon",
  [SpeechTranslationLanguage.Klingon_plqaD]: "Klingon (plqaD)",
  [SpeechTranslationLanguage.Korean]: "KoreanKorean",
  [SpeechTranslationLanguage.Kurdish_Central]: "Kurdish (Central)",
  [SpeechTranslationLanguage.Kurdish_Northern]: "Kurdish (Northern)",
  [SpeechTranslationLanguage.Lao]: "Lao",
  [SpeechTranslationLanguage.Latvian]: "Latvian",
  [SpeechTranslationLanguage.Lithuanian]: "Lithuanian",
  [SpeechTranslationLanguage.Malagasy]: "Malagasy",
  [SpeechTranslationLanguage.Malay]: "Malay",
  [SpeechTranslationLanguage.Malayalam]: "Malayalam",
  [SpeechTranslationLanguage.Maltese]: "Maltese",
  [SpeechTranslationLanguage.Maori]: "Maori",
  [SpeechTranslationLanguage.Marathi]: "Marathi",
  [SpeechTranslationLanguage.Myanmar]: "Myanmar",
  [SpeechTranslationLanguage.Nepali]: "Nepali",
  [SpeechTranslationLanguage.Norwegian]: "Norwegian",
  [SpeechTranslationLanguage.Odia]: "Odia",
  [SpeechTranslationLanguage.Pashto]: "Pashto",
  [SpeechTranslationLanguage.Persian]: "Persian",
  [SpeechTranslationLanguage.Polish]: "Polish",
  [SpeechTranslationLanguage.Portuguese_Brazil]: "Portuguese (Brazil)",
  [SpeechTranslationLanguage.Portuguese_Portugal]: "Portuguese (Portugal)",
  [SpeechTranslationLanguage.Punjabi]: "Punjabi",
  [SpeechTranslationLanguage.Queretaro_Otomi]: "Queretaro Otomi",
  [SpeechTranslationLanguage.Romanian]: "Romanian",
  [SpeechTranslationLanguage.Russian]: "Russian",
  [SpeechTranslationLanguage.Samoan]: "Samoan",
  [SpeechTranslationLanguage.Serbian_Cyrillic]: "Serbian (Cyrillic)",
  [SpeechTranslationLanguage.Serbian_Latin]: "Serbian (Latin)",
  [SpeechTranslationLanguage.Slovak]: "Slovak",
  [SpeechTranslationLanguage.Slovenian]: "Slovenian",
  [SpeechTranslationLanguage.Spanish]: "Spanish",
  [SpeechTranslationLanguage.Swahili]: "Swahili",
  [SpeechTranslationLanguage.Swedish]: "Swedish",
  [SpeechTranslationLanguage.Tahitian]: "Tahitian",
  [SpeechTranslationLanguage.Tamil]: "Tamil",
  [SpeechTranslationLanguage.Telugu]: "Telugu",
  [SpeechTranslationLanguage.Thai]: "Thai",
  [SpeechTranslationLanguage.Tigrinya]: "Tigrinya",
  [SpeechTranslationLanguage.Tongan]: "Tongan",
  [SpeechTranslationLanguage.Turkish]: "Turkish",
  [SpeechTranslationLanguage.Ukrainian]: "Ukrainian",
  [SpeechTranslationLanguage.Urdu]: "Urdu",
  [SpeechTranslationLanguage.Vietnamese]: "Vietnamese",
  [SpeechTranslationLanguage.Welsh]: "Welsh",
  [SpeechTranslationLanguage.Yucatec_Maya]: "Yucatec Maya",
}
