//https://docs.microsoft.com/en-us/azure/cognitive-services/speech-service/language-support
export enum SpeechServiceLocale {
  Arabic_Algeria = "ar-DZ",
  Arabic_Bahrain_modern_standard = "ar-BH",
  Arabic_Egypt = "ar-EG",
  Arabic_Iraq = "ar-IQ",
  Arabic_Israel = "ar-IL",
  Arabic_Jordan = "ar-JO",
  Arabic_Kuwait = "ar-KW",
  Arabic_Lebanon = "ar-LB",
  Arabic_Libya = "ar-LY",
  Arabic_Morocco = "ar-MA",
  Arabic_Oman = "ar-OM",
  Arabic_Qatar = "ar-QA",
  Arabic_Saudi_Arabia = "ar-SA",
  Arabic_Palestinian_Authority = "ar-PS",
  Arabic_Syria = "ar-SY",
  Arabic_Tunisia = "ar-TN",
  Arabic_United_Arab_Emirates = "ar-AE",
  Arabic_Yemen = "ar-YE",
  Bulgarian_Bulgaria = "bg-BG",
  Catalan_Spain = "ca-ES",
  Chinese_Cantonese_Traditional = "zh-HK",
  Chinese_Mandarin_Simplified = "zh-CN",
  Chinese_Taiwanese_Mandarin = "zh-TW",
  Croatian_Croatia = "hr-HR",
  Czech_Czech = "cs-CZ",
  Danish_Denmark = "da-DK",
  Dutch_Netherlands = "nl-NL",
  English_Australia = "en-AU",
  English_Canada = "en-CA",
  English_Ghana = "en-GH",
  English_Hong_Kong = "en-HK",
  English_India = "en-IN",
  English_Ireland = "en-IE",
  English_Kenya = "en-KE",
  English_New_Zealand = "en-NZ",
  English_Nigeria = "en-NG",
  English_Philippines = "en-PH",
  English_Singapore = "en-SG",
  English_South_Africa = "en-ZA",
  English_Tanzania = "en-TZ",
  English_United_Kingdom = "en-GB",
  English_United_States = "en-US",
  Estonian_Estonia = "et-EE",
  Filipino_Philippines = "il-PH",
  Finnish_Finland = "fi-FI",
  French_Canada = "fr-CA",
  French_France = "fr-FR",
  French_Switzerland = "fr-CH",
  German_Austria = "de-AT",
  German_Switzerland = "de-CH",
  German_Germany = "de-DE",
  Greek_Greece = "el-GR",
  Gujarati_Indian = "gu-IN",
  Hebrew_Israel = "he-IL",
  Hindi_India = "hi-IN",
  Hungarian_Hungary = "hu-HU",
  Indonesian_Indonesia = "id-ID",
  Irish_Ireland = "ga-IE",
  Italian_Italy = "it-IT",
  Japanese_Japan = "ja-JP",
  Kannada_India = "kn-IN",
  Korean_Korea = "ko-KR",
  Latvian_Latvia = "lv-LV",
  Lithuanian_Lithuania = "lt-LT",
  Malay_Malaysia = "ms-MY",
  Maltese_Malta = "mt-MT",
  Marathi_India = "mr-IN",
  Norwegian_Bokmål_Norway = "nb-NO",
  Persian_Iran = "fa-IR",
  Polish_Poland = "pl-PL",
  Portuguese_Brazil = "pt-BR",
  Portuguese_Portugal = "pt-PT",
  Romanian_Romania = "ro-RO",
  Russian_Russia = "ru-RU",
  Slovak_Slovakia = "sk-SK",
  Slovenian_Slovenia = "sl-SI",
  Spanish_Argentina = "es-AR",
  Spanish_Bolivia = "es-BO",
  Spanish_Chile = "es-CL",
  Spanish_Colombia = "es-CO",
  Spanish_Costa_Rica = "es-CR",
  Spanish_Cuba = "es-CU",
  Spanish_Dominican_Republic = "es-DO",
  Spanish_Ecuador = "es-EC",
  Spanish_El_Salvador = "es-SV",
  Spanish_Equatorial_Guinea = "es-GQ",
  Spanish_Guatemala = "es-GT",
  Spanish_Honduras = "es-HN",
  Spanish_Mexico = "es-MX",
  Spanish_Nicaragua = "es-NI",
  Spanish_Panama = "es-PA",
  Spanish_Paraguay = "es-PY",
  Spanish_Peru = "es-PE",
  Spanish_Puerto_Rico = "es-PR",
  Spanish_Spain = "es-ES",
  Spanish_Uruguay = "es-UY",
  Spanish_USA = "es-US",
  Spanish_Venezuela = "es-VE",
  Swahili_Kenya = "sw-KE",
  Swedish_Sweden = "sv-SE",
  Tamil_India = "ta-IN",
  Telugu_India = "te-IN",
  Thai_Thailand = "th-TH",
  Turkish_Turkey = "tr-TR",
  Vietnamese_Vietnam = "vi-VN",
}

export const SpeechServiceLanguagesNames: {
  [id in SpeechServiceLocale]: string;
} = {
  [SpeechServiceLocale.Arabic_Algeria]: "Arabic (Algeria)",
  [SpeechServiceLocale.Arabic_Bahrain_modern_standard]:
    "Arabic (Bahrain), modern standard",
  [SpeechServiceLocale.Arabic_Egypt]: "Arabic (Egypt)",
  [SpeechServiceLocale.Arabic_Iraq]: "Arabic (Iraq)",
  [SpeechServiceLocale.Arabic_Israel]: "Arabic (Israel)",
  [SpeechServiceLocale.Arabic_Jordan]: "Arabic (Jordan)",
  [SpeechServiceLocale.Arabic_Kuwait]: "Arabic (Kuwait)",
  [SpeechServiceLocale.Arabic_Lebanon]: "Arabic (Lebanon)",
  [SpeechServiceLocale.Arabic_Libya]: "Arabic (Libya)",
  [SpeechServiceLocale.Arabic_Morocco]: "Arabic (Morocco)",
  [SpeechServiceLocale.Arabic_Oman]: "Arabic (Oman)",
  [SpeechServiceLocale.Arabic_Qatar]: "Arabic (Palestinian Authority)",
  [SpeechServiceLocale.Arabic_Saudi_Arabia]: "Arabic (Qatar)",
  [SpeechServiceLocale.Arabic_Palestinian_Authority]: "Arabic (Saudi Arabia)",
  [SpeechServiceLocale.Arabic_Syria]: "Arabic (Syria)",
  [SpeechServiceLocale.Arabic_Tunisia]: "Arabic (Tunisia)",
  [SpeechServiceLocale.Arabic_United_Arab_Emirates]:
    "Arabic (United Arab Emirates)",
  [SpeechServiceLocale.Arabic_Yemen]: "Arabic (Yemen)",
  [SpeechServiceLocale.Bulgarian_Bulgaria]: "Bulgarian (Bulgaria)",
  [SpeechServiceLocale.Catalan_Spain]: "Catalan (Spain)",
  [SpeechServiceLocale.Chinese_Cantonese_Traditional]:
    "Chinese (Cantonese, Traditional)",
  [SpeechServiceLocale.Chinese_Mandarin_Simplified]:
    "Chinese (Mandarin, Simplified)",
  [SpeechServiceLocale.Chinese_Taiwanese_Mandarin]:
    "Chinese (Taiwanese Mandarin)",
  [SpeechServiceLocale.Croatian_Croatia]: "Croatian (Croatia)",
  [SpeechServiceLocale.Czech_Czech]: "Czech (Czech)",
  [SpeechServiceLocale.Danish_Denmark]: "Danish (Denmark)",
  [SpeechServiceLocale.Dutch_Netherlands]: "Dutch (Netherlands)",
  [SpeechServiceLocale.English_Australia]: "English (Australia)",
  [SpeechServiceLocale.English_Canada]: "English (Canada)",
  [SpeechServiceLocale.English_Ghana]: "English (Ghana)",
  [SpeechServiceLocale.English_Hong_Kong]: "English (Hong Kong)",
  [SpeechServiceLocale.English_India]: "English (India)",
  [SpeechServiceLocale.English_Ireland]: "English (Ireland)",
  [SpeechServiceLocale.English_Kenya]: "English (Kenya)",
  [SpeechServiceLocale.English_New_Zealand]: "English (New Zealand)",
  [SpeechServiceLocale.English_Nigeria]: "English (Nigeria)",
  [SpeechServiceLocale.English_Philippines]: "English (Philippines)",
  [SpeechServiceLocale.English_Singapore]: "English (Singapore)",
  [SpeechServiceLocale.English_South_Africa]: "English (South Africa)",
  [SpeechServiceLocale.English_Tanzania]: "English (Tanzania)",
  [SpeechServiceLocale.English_United_Kingdom]: "English (United Kingdom)",
  [SpeechServiceLocale.English_United_States]: "English (United States)",
  [SpeechServiceLocale.Estonian_Estonia]: "Estonian (Estonia)",
  [SpeechServiceLocale.Filipino_Philippines]: "Filipino (Philippines)",
  [SpeechServiceLocale.Finnish_Finland]: "Finnish (Finland)",
  [SpeechServiceLocale.French_Canada]: "French (Canada)",
  [SpeechServiceLocale.French_France]: "French (France)",
  [SpeechServiceLocale.French_Switzerland]: "French (Switzerland)",
  [SpeechServiceLocale.German_Austria]: "German (Austria)",
  [SpeechServiceLocale.German_Switzerland]: "German (Switzerland)",
  [SpeechServiceLocale.German_Germany]: "German (Germany)",
  [SpeechServiceLocale.Greek_Greece]: "Greek (Greece)",
  [SpeechServiceLocale.Gujarati_Indian]: "Gujarati (Indian)",
  [SpeechServiceLocale.Hebrew_Israel]: "Hebrew (Israel)",
  [SpeechServiceLocale.Hindi_India]: "Hindi (India)",
  [SpeechServiceLocale.Hungarian_Hungary]: "Hungarian (Hungary)",
  [SpeechServiceLocale.Indonesian_Indonesia]: "Indonesian (Indonesia)",
  [SpeechServiceLocale.Irish_Ireland]: "Irish (Ireland)",
  [SpeechServiceLocale.Italian_Italy]: "Italian (Italy)",
  [SpeechServiceLocale.Japanese_Japan]: "Japanese (Japan)",
  [SpeechServiceLocale.Kannada_India]: "Kannada (India)",
  [SpeechServiceLocale.Korean_Korea]: "Korean (Korea)",
  [SpeechServiceLocale.Latvian_Latvia]: "Latvian (Latvia)",
  [SpeechServiceLocale.Lithuanian_Lithuania]: "Lithuanian (Lithuania)",
  [SpeechServiceLocale.Malay_Malaysia]: "Malay (Malaysia)",
  [SpeechServiceLocale.Maltese_Malta]: "Maltese (Malta)",
  [SpeechServiceLocale.Marathi_India]: "Marathi (India)",
  [SpeechServiceLocale.Norwegian_Bokmål_Norway]: "Norwegian (Bokmål, Norway)",
  [SpeechServiceLocale.Persian_Iran]: "Persian (Iran)",
  [SpeechServiceLocale.Polish_Poland]: "Polish (Poland)",
  [SpeechServiceLocale.Portuguese_Brazil]: "Portuguese (Brazil)",
  [SpeechServiceLocale.Portuguese_Portugal]: "Portuguese (Portugal)",
  [SpeechServiceLocale.Romanian_Romania]: "Romanian (Romania)",
  [SpeechServiceLocale.Russian_Russia]: "Russian (Russia)",
  [SpeechServiceLocale.Slovak_Slovakia]: "Slovak (Slovakia)",
  [SpeechServiceLocale.Slovenian_Slovenia]: "Slovenian (Slovenia)",
  [SpeechServiceLocale.Spanish_Argentina]: "Spanish (Argentina)",
  [SpeechServiceLocale.Spanish_Bolivia]: "Spanish (Bolivia)",
  [SpeechServiceLocale.Spanish_Chile]: "Spanish (Chile)",
  [SpeechServiceLocale.Spanish_Colombia]: "Spanish (Colombia)",
  [SpeechServiceLocale.Spanish_Costa_Rica]: "Spanish (Costa Rica)",
  [SpeechServiceLocale.Spanish_Cuba]: "Spanish (Cuba)",
  [SpeechServiceLocale.Spanish_Dominican_Republic]:
    "Spanish (Dominican Republic)",
  [SpeechServiceLocale.Spanish_Ecuador]: "Spanish (Ecuador)",
  [SpeechServiceLocale.Spanish_El_Salvador]: "Spanish (El Salvador)",
  [SpeechServiceLocale.Spanish_Equatorial_Guinea]:
    "Spanish (Equatorial Guinea)",
  [SpeechServiceLocale.Spanish_Guatemala]: "Spanish (Guatemala)",
  [SpeechServiceLocale.Spanish_Honduras]: "Spanish (Honduras)",
  [SpeechServiceLocale.Spanish_Mexico]: "Spanish (Mexico)",
  [SpeechServiceLocale.Spanish_Nicaragua]: "Spanish (Nicaragua)",
  [SpeechServiceLocale.Spanish_Panama]: "Spanish (Panama)",
  [SpeechServiceLocale.Spanish_Paraguay]: "Spanish (Paraguay)",
  [SpeechServiceLocale.Spanish_Peru]: "Spanish (Peru)",
  [SpeechServiceLocale.Spanish_Puerto_Rico]: "Spanish (Puerto Rico)",
  [SpeechServiceLocale.Spanish_Spain]: "Spanish (Spain)",
  [SpeechServiceLocale.Spanish_Uruguay]: "Spanish (Uruguay)",
  [SpeechServiceLocale.Spanish_USA]: "Spanish (USA)",
  [SpeechServiceLocale.Spanish_Venezuela]: "Spanish (Venezuela)",
  [SpeechServiceLocale.Swahili_Kenya]: "Swahili (Kenya)",
  [SpeechServiceLocale.Swedish_Sweden]: "Swedish (Sweden)",
  [SpeechServiceLocale.Tamil_India]: "Tamil (India)",
  [SpeechServiceLocale.Telugu_India]: "Telugu (India)",
  [SpeechServiceLocale.Thai_Thailand]: "Thai (Thailand)",
  [SpeechServiceLocale.Turkish_Turkey]: "Turkish (Turkey)",
  [SpeechServiceLocale.Vietnamese_Vietnam]: "Vietnamese (Vietnam)",
};

//https://docs.microsoft.com/en-us/azure/cognitive-services/speech-service/language-support#speech-translation
export enum SpeechTranslationLanguage {
  Afrikaans = "af",
  Albanian = "sq",
  Amharic = "am",
  Arabic = "ar",
  Armenian = "hy",
  Assamese = "as",
  Azerbaijani = "az",
  Bangla = "bn",
  Bosnian_Latin = "bs",
  Bulgarian = "bg",
  Cantonese_Traditional = "yue",
  Catalan = "ca",
  Chinese_Literary = "lzh",
  Chinese_Simplified = "zh-Hans",
  Chinese_Traditional = "zh-Hant",
  Croatian = "hr",
  Czech = "cs",
  Danish = "da",
  Dari = "prs",
  Dutch = "nl",
  English = "en",
  Estonian = "et",
  Fijian = "fj",
  Filipino = "fil",
  Finnish = "fi",
  French = "fr",
  French_Canada = "fr-ca",
  German = "de",
  Greek = "el",
  Gujarati = "gu",
  Haitian_Creole = "ht",
  Hebrew = "he",
  Hindi = "hi",
  Hmong_Daw = "mww",
  Hungarian = "hu",
  Icelandic = "is",
  Indonesian = "id",
  Inuktitut = "iu",
  Irish = "ga",
  Italian = "it",
  Japanese = "ja",
  Kannada = "kn",
  Kazakh = "kk",
  Khmer = "km",
  Klingon = "tlh-Latn",
  Klingon_plqaD = "tlh-Piqd",
  Korean = "ko",
  Kurdish_Central = "ku",
  Kurdish_Northern = "kmr",
  Lao = "lo",
  Latvian = "lv",
  Lithuanian = "lt",
  Malagasy = "mg",
  Malay = "ms",
  Malayalam = "ml",
  Maltese = "mt",
  Maori = "mi",
  Marathi = "mr",
  Myanmar = "my",
  Nepali = "ne",
  Norwegian = "nb",
  Odia = "or",
  Pashto = "ps",
  Persian = "fa",
  Polish = "pl",
  Portuguese_Brazil = "pt",
  Portuguese_Portugal = "pt-pt",
  Punjabi = "pa",
  Queretaro_Otomi = "otq",
  Romanian = "ro",
  Russian = "ru",
  Samoan = "sm",
  Serbian_Cyrillic = "sr-Cyrl",
  Serbian_Latin = "sr-Latn",
  Slovak = "sk",
  Slovenian = "sl",
  Spanish = "es",
  Swahili = "sw",
  Swedish = "sv",
  Tahitian = "ty",
  Tamil = "ta",
  Telugu = "te",
  Thai = "th",
  Tigrinya = "ti",
  Tongan = "to",
  Turkish = "tr",
  Ukrainian = "uk",
  Urdu = "ur",
  Vietnamese = "vi",
  Welsh = "cy",
  Yucatec_Maya = "yua",
}

export const SpeechTranslationLanguagesNames: {
  [id in SpeechTranslationLanguage]: string;
} = {
  [SpeechTranslationLanguage.Afrikaans]: "Afrikaans",
  [SpeechTranslationLanguage.Albanian]: "Albanian",
  [SpeechTranslationLanguage.Amharic]: "Amharic",
  [SpeechTranslationLanguage.Arabic]: "Arabic",
  [SpeechTranslationLanguage.Armenian]: "Armenian",
  [SpeechTranslationLanguage.Assamese]: "Assamese",
  [SpeechTranslationLanguage.Azerbaijani]: "Azerbaijani",
  [SpeechTranslationLanguage.Bangla]: "Bangla",
  [SpeechTranslationLanguage.Bosnian_Latin]: "Bosnian (Latin)",
  [SpeechTranslationLanguage.Bulgarian]: "Bulgarian",
  [SpeechTranslationLanguage.Cantonese_Traditional]: "Cantonese (Traditional)",
  [SpeechTranslationLanguage.Catalan]: "Catalan",
  [SpeechTranslationLanguage.Chinese_Literary]: "Chinese (Literary)",
  [SpeechTranslationLanguage.Chinese_Simplified]: "Chinese Simplified",
  [SpeechTranslationLanguage.Chinese_Traditional]: "Chinese Traditional",
  [SpeechTranslationLanguage.Croatian]: "Croatian",
  [SpeechTranslationLanguage.Czech]: "Czech",
  [SpeechTranslationLanguage.Danish]: "Danish",
  [SpeechTranslationLanguage.Dari]: "Dari",
  [SpeechTranslationLanguage.Dutch]: "Dutch",
  [SpeechTranslationLanguage.English]: "English",
  [SpeechTranslationLanguage.Estonian]: "Estonian",
  [SpeechTranslationLanguage.Fijian]: "Fijian",
  [SpeechTranslationLanguage.Filipino]: "Filipino",
  [SpeechTranslationLanguage.Finnish]: "Finnish",
  [SpeechTranslationLanguage.French]: "French",
  [SpeechTranslationLanguage.French_Canada]: "French (Canada)",
  [SpeechTranslationLanguage.German]: "German",
  [SpeechTranslationLanguage.Greek]: "Greek",
  [SpeechTranslationLanguage.Gujarati]: "Gujarati",
  [SpeechTranslationLanguage.Haitian_Creole]: "Haitian Creole",
  [SpeechTranslationLanguage.Hebrew]: "Hebrew",
  [SpeechTranslationLanguage.Hindi]: "Hindi",
  [SpeechTranslationLanguage.Hmong_Daw]: "Hmong Daw",
  [SpeechTranslationLanguage.Hungarian]: "Hungarian",
  [SpeechTranslationLanguage.Icelandic]: "Icelandic",
  [SpeechTranslationLanguage.Indonesian]: "Indonesian",
  [SpeechTranslationLanguage.Inuktitut]: "Inuktitut",
  [SpeechTranslationLanguage.Irish]: "Irish",
  [SpeechTranslationLanguage.Italian]: "Italian",
  [SpeechTranslationLanguage.Japanese]: "Japanese",
  [SpeechTranslationLanguage.Kannada]: "Kannada",
  [SpeechTranslationLanguage.Kazakh]: "Kazakh",
  [SpeechTranslationLanguage.Khmer]: "Khmer",
  [SpeechTranslationLanguage.Klingon]: "Klingon",
  [SpeechTranslationLanguage.Klingon_plqaD]: "Klingon (plqaD)",
  [SpeechTranslationLanguage.Korean]: "KoreanKorean",
  [SpeechTranslationLanguage.Kurdish_Central]: "Kurdish (Central)",
  [SpeechTranslationLanguage.Kurdish_Northern]: "Kurdish (Northern)",
  [SpeechTranslationLanguage.Lao]: "Lao",
  [SpeechTranslationLanguage.Latvian]: "Latvian",
  [SpeechTranslationLanguage.Lithuanian]: "Lithuanian",
  [SpeechTranslationLanguage.Malagasy]: "Malagasy",
  [SpeechTranslationLanguage.Malay]: "Malay",
  [SpeechTranslationLanguage.Malayalam]: "Malayalam",
  [SpeechTranslationLanguage.Maltese]: "Maltese",
  [SpeechTranslationLanguage.Maori]: "Maori",
  [SpeechTranslationLanguage.Marathi]: "Marathi",
  [SpeechTranslationLanguage.Myanmar]: "Myanmar",
  [SpeechTranslationLanguage.Nepali]: "Nepali",
  [SpeechTranslationLanguage.Norwegian]: "Norwegian",
  [SpeechTranslationLanguage.Odia]: "Odia",
  [SpeechTranslationLanguage.Pashto]: "Pashto",
  [SpeechTranslationLanguage.Persian]: "Persian",
  [SpeechTranslationLanguage.Polish]: "Polish",
  [SpeechTranslationLanguage.Portuguese_Brazil]: "Portuguese (Brazil)",
  [SpeechTranslationLanguage.Portuguese_Portugal]: "Portuguese (Portugal)",
  [SpeechTranslationLanguage.Punjabi]: "Punjabi",
  [SpeechTranslationLanguage.Queretaro_Otomi]: "Queretaro Otomi",
  [SpeechTranslationLanguage.Romanian]: "Romanian",
  [SpeechTranslationLanguage.Russian]: "Russian",
  [SpeechTranslationLanguage.Samoan]: "Samoan",
  [SpeechTranslationLanguage.Serbian_Cyrillic]: "Serbian (Cyrillic)",
  [SpeechTranslationLanguage.Serbian_Latin]: "Serbian (Latin)",
  [SpeechTranslationLanguage.Slovak]: "Slovak",
  [SpeechTranslationLanguage.Slovenian]: "Slovenian",
  [SpeechTranslationLanguage.Spanish]: "Spanish",
  [SpeechTranslationLanguage.Swahili]: "Swahili",
  [SpeechTranslationLanguage.Swedish]: "Swedish",
  [SpeechTranslationLanguage.Tahitian]: "Tahitian",
  [SpeechTranslationLanguage.Tamil]: "Tamil",
  [SpeechTranslationLanguage.Telugu]: "Telugu",
  [SpeechTranslationLanguage.Thai]: "Thai",
  [SpeechTranslationLanguage.Tigrinya]: "Tigrinya",
  [SpeechTranslationLanguage.Tongan]: "Tongan",
  [SpeechTranslationLanguage.Turkish]: "Turkish",
  [SpeechTranslationLanguage.Ukrainian]: "Ukrainian",
  [SpeechTranslationLanguage.Urdu]: "Urdu",
  [SpeechTranslationLanguage.Vietnamese]: "Vietnamese",
  [SpeechTranslationLanguage.Welsh]: "Welsh",
  [SpeechTranslationLanguage.Yucatec_Maya]: "Yucatec Maya",
};
